### PR TITLE
add category support

### PR DESCRIPTION
**Pull request by nnnkit**

### CODE REVIEW

**Comment by brotzky** [comment]
Hey, haven't forgotten about this. It's super busy at work and we haven't had the full amount of time to review and integrate this.

**Comment by brotzky** [comment]
had a chance to look over it -- fantastic.

Will now have to get on the design aspect of it. And docs!

**Comment by nnnkit** [comment]
Perfect, will be happy to work on docs.

**Comment by MatthewTrout** [comment]
@nnnkit any reason you went with categories rather than tags? Just interested, was looking at tags myself then found this PR!

**Comment by nnnkit** [comment]
@nnnkit lots of people were asking about categories. They both works similarly. I am thinking of implementing tags too if @brotzky is okay with.

**Comment by brotzky** [comment]
I think supporting both is overkill. I'd go for one or the other. Personally, I find them similar enough to serve the same function for Novela.

If either of you have a preference for tags or categories we can adjust the naming of this PR accordingly.

**Comment by nnnkit** [comment]
@brotzky I feel that too it will be over crowded. I feel `tags` is better and simple. You can decide on that

**Comment by MatthewTrout** [comment]
Agree no sense to have more than one concept of categorisation. For me, categories imply a one-to-one relationship, whereas tags are typically used to allow multiple classifications. Although tags are usually free-form and maybe less semantic, in this case I think for blog posts, the flexibility of categorising a post with multiple themes, and therefore the definition of tag, feels more appropriate. That’s just my two cents though!

**Comment by hadifarnoud** [comment]
can't wait for this. I also want to add Wordpress support. Probably best to have tags and categories sorted though

**Comment by brotzky** [comment]
We'll go with `tags` as a naming convention. Thanks for the feedback @MatthewTrout and @nnnkit.

**Pull request merged**
