### PR TITLE
update react-medium-image-zoom, v3 to v4

### PR DESCRIPTION
**Pull request by eugenejeonme**
# Checklist:

* [x] I have followed the guidelines in our [Contributing Guidelines](https://github.com/narative/gatsby-theme-novela/blob/master/CONTRIBUTING.md). _Especially our commitlint_
* [x] I have checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/fix/change.
* [x] I have checked for an open issue related to this. _There isn't one / There is one : #XXX_
* [x] I have performed a self-review of my own code.
* [x] I have performed the necessary tests locally.
* [x] I have linted my code locally prior to submission.
* [x] If applicable, I have commented my code, particularly in hard-to-understand areas

# Type of PR

* [ ] Bug fix (_non-breaking change which fixes an issue_)
* [ ] New feature (_adding a feature following a feature-request issue_)
* [ ] Improvement (_improving an existing feature - includes `style:` and `perf:`commits_)
* [x] Refactor (_rewriting existing code without any feature change_)
* [ ] (!) This change is or requires a documentation update

# Description
* Upgrade [react-medium-image-zoom](https://github.com/rpearce/react-medium-image-zoom#controlled-component-controlled), v3 to v4.
* Retain existing functionality.

### CODE REVIEW

**Comment by brotzky** [comment]
Simple PR and helpful. Thanks a ton <3

**Comment by rpearce** [comment]
As the author of `react-medium-image-zoom`, this is super cool to see implemented in the wild! Hope it was easy to upgrade, and I hope it's working 👌

**Comment by brotzky** [comment]
Thanks @rpearce. V3 was working great and im sure V4 will as well.
Check it out in action here: https://novela.narative.co/Understanding-the-Gatsby-lifecycle-with-Narative

**Comment by rpearce** [comment]
Looks good. I'll have some more updates coming in the near future to make it even better

**Pull request merged**
