### PR TITLE
feat: add auth0 for secret pages access

### PR DESCRIPTION
**Pull request by lwz7512**
Hi novela code owners:

I created a new branch for secret pages access with auth0, please review it.
I know its not possible to merge into master branch, but if it could be accepted as a new branch, it would be great!

### CODE REVIEW

**Comment by brotzky** [comment]
This is really cool. Any way you can link to a working example? (Or the preview may work?)

A Branch on the theme could be a great idea. I do agree it's probably overkill for most of the default users.

**Comment by lwz7512** [comment]
Done, demo is [here](https://novela-auth0-demo.netlify.com/) , click the user icon in the top navbar to start auth0 login.

**Comment by brotzky** [comment]
Sweet. Could you merge this into an auth0 branch?

And we'll add documentation/a link on `master` README for people to find it :)

**Comment by lwz7512** [comment]
how to do that? I didn't see auth0 branch in this repository.

**Comment by brotzky** [comment]
My bad! I've made you one.  https://github.com/narative/gatsby-theme-novela/tree/auth0

**Comment by brotzky** [comment]
Feel free to make a PR to add documentation to the README to point to the branch example.

**Comment by lwz7512** [comment]
Great!

**Pull request merged**
