### PR TITLE
fix: Long words, text, or URL links could break the article layout (small resolutions)

### PR DESCRIPTION
**Pull request by JoseJesusOchoaTorres**
# Checklist:

* [x] I have followed the guidelines in our [Contributing Guidelines](https://github.com/narative/gatsby-theme-novela/blob/master/CONTRIBUTING.md). _Especially our commitlint_
* [x] I have checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/fix/change.
* [x] I have checked for an open issue related to this. _There isn't one / There is one : #XXX_
* [x] I have performed a self-review of my own code.
* [ ] I have performed the necessary tests locally.
* [ ] I have linted my code locally prior to submission.
* [ ] If applicable, I have commented my code, particularly in hard-to-understand areas

# Type of PR

* [x] Bugfix (_non-breaking change which fixes an issue_)
* [ ] New feature (_adding a feature following a feature-request issue_)
* [ ] Improvement (_improving an existing feature - includes `style:` and `perf:`commits_)
* [ ] Refactor (_rewriting existing code without any feature change_)
* [ ] (!) This change is or requires a documentation update

# Description

Hey there, I published my first article using this theme and I have detected that this theme is not using the `line-break` CSS property; if we are not using it, all long words, text, or URL links can break the layout.

## Additional information/context
Maybe my comments above are not so clear, but screen captures can help.

This is my blog article where you can replicate the issue:
https://josejesus.dev/Crea-tu-propio-grid-system

At the end of my article, I added two links:

image

You can resize the browser window in small resolutions to confirm how long words/text can break the article layout.

image

It could be solved easily with the `line-break: anywhere` rule in the `:root` element.

image

### CODE REVIEW

**Comment by brotzky** [comment]
thanks @joeljacobdev

**Comment by brotzky** [comment]
thanks @JoseJesusOchoaTorres

**Comment by Tommrodrigues** [comment]
Hi there, this is a breaking change as seen below, it negatively impacts other parts of the site by putting the line break anywhere in the sentence (note the hero text and the author bio, but also affects other areas e.g. date within article):

Screenshot 2020-10-29 at 12 07 23

**Comment by JoseJesusOchoaTorres** [comment]
Hey, @Tommrodrigues good catch.

A better approach to solve my issue could be to change the word-break property in the anchor tags of an article, in that way we can avoid affecting more elements. My apologies @brotzky for this breaking change.

**Pull request merged**
