### PR TITLE
Continuous Integration (Linting)

### LINKED ISSUE #52: Continuous Integration
Would you folks like me to set up CI for this repo so we can start quality checking the contributions.? If so, I would like to suggest [Github workflows](https://developer.github.com/actions/managing-workflows/) as this will become the de-facto standard IMO. I think you might [need to register here](https://github.com/features/actions) first.

If we do this the PR can be used to preview the result which can then be used to discuss the definitive workflow (build, linting, test, etc.) in more detail. FYI this would be an incremental process so we will start simple, then improve from there. Once it is perfect we could even consider Continuous Deployment for automated releases.

Taken from another repo but to give an idea of what I mean:

image

### PR DESCRIPTION
**Pull request by bravo-kernel**
This PR closes #52.

Contains the following subjects

## CI Linting

To enforce code consistency

- [x] add `yarn lint` run script 
- [x] add eslint with [airbnb](https://github.com/airbnb/javascript) and [unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn) style guides
- [x] add prettier
- [x] add custom unicorn rule to allow both kebab-case and camelCase filenames
- [x] add `.travis.yml` to execute linting (and placeholder matrix for tests)

> Please note that the linting errors should be fixed outside this PR.

## CI Dependencies

To make sure dependencies stay up-to-date:

- [x] prepare `.travis.yml` for greenkeeper
- [x] @brotzky: enable greenkeeper

## Pre-commit hooks

Adding pre-commit hooks will greatly improve development speed and the quality of contributions. When a user does a `git commit` Husky will first run `yarn lint` locally and will not allow the commit unless linting passes.

- [x] add husky
- [x] add `yarn lint` pre-commit hook

> until eslint errors are fixed use `--no-verify` to bypass husky

## Continuous Deployment

Excluded from this PR because the intended solution (release-it) does not support yarn workspaces so an alternative needs to be investigated, possibly lerna.

### CODE REVIEW

**Comment by bravo-kernel** [comment]
@brotzky as step 1 I have added a run script for linting so we have something to start with.

- I chose to place this inside the root so we can use it for both www and theme workspaces
- the alternative would be using lerna but that would lead to more complexity
- you might try locally to see what happens, `yarn install`, then `yarn lint`
- those warnings are valid IMO and should be fixed (not necessarily in this PR)

> I have no idea why the Netlify checks above are failing but could be related to this change.

ps: I had to comment out line 22 in the theme's `src/types/store.d.ts` file, it was breaking eslint.

The next steps:

1. Travis
2. Husky (so we can run `yarn lint` as a pre-commit hook effectively enforcing users to PR valid code)

**Comment by bravo-kernel** [comment]
@brotzky have you enabled Travis for this repository?

**Comment by bravo-kernel** [comment]
Looks like I will have to put back the yarn lock file. Will do so we keep this PR on focus.

**Comment by bravo-kernel** [comment]
@brotzky I don't want to rush you but could you give some priority to enabling Travis as it is blocking progress and I have limited time left.

**Comment by bravo-kernel** [comment]
Thanks
------ Original Message ------

**Comment by bravo-kernel** [comment]
**CI Linting** is done and works as expected as can be seen in [the Travis log](https://travis-ci.org/narative/gatsby-theme-novela/jobs/577738623). I have rebased the commits and have updated the original ticket (please check for details).

Fixing the linting errors is quite easy. I personally:
-  start with fixing the prettier errors. With VSCode and [this extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) it is as simple as opening the file, then CTRL + SHIFT + P, then "Format Document" and all fixes will be applied
- what remains then are the eslint errors and those are well described, always using an url-suffix. E.g. `strict` doc found at https://eslint.org/docs/rules/strict

If you have questions or feedback on this topic, let me know.

> ps: could you please enable greenkeeper so we can finish that as well?

**Comment by bravo-kernel** [comment]
@brotzky this PR is good to merge unless you have questions/comments. Changes were rebased against current master.

I have decided to not include CD in this PR because extra work is needed to get release-it working with the yarn workspaces. This way nothing gets blocked. I hope you are as pleased with this first step as I am.

**Comment by bravo-kernel** [comment]
No rush, take your time and if you have any questions or change-requests do not hesitate to ask.

**Comment by bravo-kernel** [comment]
Apologies if I caused confusion just now. I was test-running lerna but forgot to check out a new branch 😢

**Comment by brotzky** [comment]
Looks pretty good. If we run into linting being too annoying I'll make them more lenient in the future.

Would love to get release-it working somehow. Or a project similar to that.

**Comment by bravo-kernel** [comment]
Thanks. I was scared of it being obtrusive in the beginning as well but for me it has worked as some sort of mentor, the tips make sense and after a while putting in the "correct" code became second nature. Above all, it will improve the consistency of the code which should make judging PRs easier.

Once merged I will drop a PR for lerna so you can auto-deploy. I have already tested it and cannot believed I did not give that a go first, it comes with support for yarn workspaces. I will give you the details then but I think releasing from the/your commandline would be step 1. It's almost too simple.

**Comment by brotzky** [comment]
Going to test locally. The 900 warnings will be fun :D

**Pull request merged**
