### PR TITLE
Fixes component shadowing & other things

### PR DESCRIPTION
**Pull request by mabasic**
**Fixes component shadowing for all files.**

For some reason when you used eg. `Article.Hero.tsx` you could not use component shadowing on that file, but when I renamed it to eg. `ArticleHero.tsx` (without period in the middle), then I could use component shadowing. I have tested this and it works now.

To verify:

1. clone this PR & run yarn
2. use component shadowing in `/www` for any component or section
3. run `yarn develop` to verify that it works

---

Other fixes:

- Adds patreon and paypal icons. #92 
- Fixes subscription panel fade when having only one post. #95 
- Fixes Image__Large to not cause horizontal scroll to appear.
- Fixes design bugs that were causing the horizontal scroll to appear on article show. 

Design bug:

Screenshot_2019-08-27 Getting started with Novela

Fixed:

Screenshot_2019-08-27 Getting started with Novela(1)

Notice the upper black border missing the radius, that is because it went outside the screen and horizontal scroll appeared. That is also solved with this PR.

### CODE REVIEW

**Comment by mabasic** [comment]
Let me know what you decide on doing: merging or solving in gatsby because I am having trouble using my forked version of this package to finish working on my blog customizations.

Can you tell me how to publish just the `@narative/gatsby-theme-novela` directory as a new branch so that I can use that for development until this is fixed?

**Comment by mabasic** [comment]
Sure thing. I agree. Let's wait. I will reopen closed PRs and send a new one for horizontal scroll

**Comment by mabasic** [comment]
I've sent the last PR for horizontal scroll #100 that was also fixed in this PR. I will close this PR while we wait for Gatsby

**Comment by jpvalery** [comment]
Any updates from Gatsby on this?

**Comment by brotzky** [comment]
Good question! I'm not entirely sure to be honest. I've tried looking through Gatsby's PRs and can't seem to find anything related to it so far. There's a lot going on so it's possible I missed the update.

We could kindly ask @ChristopherBiscardi to update us when it's ready or link us to PR when it's available.

**Comment by ChristopherBiscardi** [comment]
https://github.com/gatsbyjs/gatsby/pull/16424 is the issue to follow. There's a standing issue with the tests where `graceful-fs` is being polyfilled causing `process` to return different values in the test code at different times. Need to fix that and then the code can land

**Pull request closed without merging**
