### PR TITLE
[Feature] gatsby-remark-vscode migration from prism

### PR DESCRIPTION
**Pull request by brotzky**

### CODE REVIEW

**Comment by brotzky** [comment]
Blocked by https://github.com/andrewbranch/gatsby-remark-vscode/issues/34
Will continue once it's fixed or will make a PR to fix it depending on timeline.

**Comment by bravo-kernel** [comment]
@brotzky this issue seems to be resolved. See https://github.com/andrewbranch/gatsby-remark-vscode/issues/34#issuecomment-523986554

**Comment by brotzky** [comment]
Closing as it seems Prism is still working well for the majority of users and it's a decent amount of work to move to VSCode.

**Comment by dcastil** [comment]
Hi @brotzky! I just wanted to open an issue to suggest replacing Prism with `gatsby-remark-vscode` and discovered this PR.

Would you like to share why it would be a decent amount of work to move to VSCode? I might be able to pick up the work for that if it's feasible and wanted.

My two biggest reasons for `gatsby-remark-vscode` are superior syntax highlighting (and the same highlighting as my editor which means no surprises) and all the compiling being done during build time, reducing the bundle size and rehydration time a lot. As far as I understand, `prism-react-renderer` tokenises the code during runtime.

**Comment by dcastil** [comment]
For documentation purposes:

Here is a screenshot of a code block on https://novela.narative.co/Understanding-the-Gatsby-lifecycle-with-Narative with Prism highlighting:

Screenshot 2020-01-10 at 22 35 08

Here is the same code with VS Code syntax highlighting:

Screenshot 2020-01-10 at 21 43 10

**Comment by brotzky** [comment]
Hey @dcastil it looks very nice :)

If you're able to tackle this that would be awesome. Keep in mind we'd like to maintain the line numbers, highlighting, copy action and mobile (and if possible the Oceanic theme or a configurable way to set the theme).

If that's possible I don't see why we'd want to keep using Prism over VSCode.

**Pull request closed without merging**
