### PR TITLE
Adding Unsplash as an option for social

### PR DESCRIPTION
**Pull request by jpvalery**
As an Unsplash contributor, I'd like to put a link to my Unsplash profile in my author profile. 

Just added the official SVG (modified to follow the model from the other icons) + an option in SocialLinks.tsx.

IDK how many options you want to provide in the end, but I feel Unsplash should be one :)

### CODE REVIEW

**Comment by brotzky** [comment]
Looks great, just resolve conflicts and we're good to go!

**Comment by jpvalery** [comment]
This was a weird conflict but I guess this worked? Let me know if you need anything else!

**Comment by jpvalery** [comment]
I'm sorry for spamming you today, but I'm now getting an error that I can't really explain.

If I try using the Unsplash option we just added, it returns the following log. And I don't understand why as this PR just added the image and one option.

`TypeError: type is undefined
isProxyType
node_modules/react-hot-loader/dist/react-hot-loader.development.js:1229

  1226 |   return idsByType.get(type);
  1227 | };
  1228 | var isProxyType = function isProxyType(type) {
> 1229 |   return type[PROXY_KEY];
  1230 | };
  1231 | 
  1232 | var getProxyById = function getProxyById(id) {

resolveProxy
node_modules/react-hot-loader/dist/react-hot-loader.development.js:1770

  1767 | }
  1768 | 
  1769 | function resolveProxy(type) {
> 1770 |   if (isProxyType(type)) {
  1771 |     return type;
  1772 |   }
  1773 | 

resolveSimpleType
node_modules/react-hot-loader/dist/react-hot-loader.development.js:1786

  1783 | }
  1784 | 
  1785 | var resolveSimpleType = function resolveSimpleType(type) {
> 1786 |   return resolveProxy(type) || resolveUtility(type) || type;
  1787 | };
  1788 | 
  1789 | var resolveType = function resolveType(type) {

patch/React$$1.createElement
node_modules/react-hot-loader/dist/react-hot-loader.development.js:2820

  2817 |       args[_key - 1] = arguments[_key];
  2818 |     }
  2819 | 
> 2820 |     return originalCreateElement.apply(undefined, [typeResolver(type)].concat(args));
  2821 |   };
  2822 |   React$$1.createElement.isPatchedByReactHotLoader = true;
  2823 | }

jsx
node_modules/@emotion/core/dist/core.browser.esm.js:102

   99 | 
  100 | if (props == null || props.css == null) {
  101 |   // $FlowFixMe
> 102 |   return createElement.apply(undefined, args);
  103 | }
  104 | 
  105 | if (process.env.NODE_ENV !== 'production' && typeof props.css === 'string' && // check if there is a css declaration

SocialLinks/<
node_modules/@narative/gatsby-theme-novela/src/components/SocialLinks/SocialLinks.tsx:41

  38 | const Icon = icons[name];
  39 | 
  40 | return (
> 41 |   <SocialIconContainer
  42 |     key={option.url}
  43 |     target="_blank"
  44 |     rel="noopener"

SocialLinks
node_modules/@narative/gatsby-theme-novela/src/components/SocialLinks/SocialLinks.tsx:34

  31 | function SocialLinks({ links, fill = "#73737D" }: SocialLinksProps) {
  32 |   if (!links) return null;
  33 | 
> 34 |   return (
  35 |     <>
  36 |       {links.map(option => {
  37 |         const name = getHostname(option.url);

renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js:15105

  15102 |   }
  15103 | }
  15104 | 
> 15105 | var children = Component(props, refOrContext);
  15106 | 
  15107 | if (didScheduleRenderPhaseUpdate) {
  15108 |   do {

updateFunctionComponent
node_modules/react-dom/cjs/react-dom.development.js:16922

  16919 | {
  16920 |   ReactCurrentOwner$3.current = workInProgress;
  16921 |   setCurrentPhase('render');
> 16922 |   nextChildren = renderWithHooks(current$$1, workInProgress, Component, nextProps, context, renderExpirationTime);
  16923 |   if (debugRenderPhaseSideEffects || debugRenderPhaseSideEffectsForStrictMode && workInProgress.mode & StrictMode) {
  16924 |     // Only double-render components with Hooks
  16925 |     if (workInProgress.memoizedState !== null) {

beginWork$1
node_modules/react-dom/cjs/react-dom.development.js:18495

  18492 |     var _Component = workInProgress.type;
  18493 |     var unresolvedProps = workInProgress.pendingProps;
  18494 |     var resolvedProps = workInProgress.elementType === _Component ? unresolvedProps : resolveDefaultProps(_Component, unresolvedProps);
> 18495 |     return updateFunctionComponent(current$$1, workInProgress, _Component, resolvedProps, renderExpirationTime);
  18496 |   }
  18497 | case ClassComponent:
  18498 |   {

callCallback
node_modules/react-dom/cjs/react-dom.development.js:348

  345 |     window.event = windowEvent;
  346 |   }
  347 | 
> 348 |   func.apply(context, funcArgs);
  349 |   didError = false;
  350 | }
  351 | 

invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:398

  395 | // Synchronously dispatch our fake event. If the user-provided function
  396 | // errors, it will trigger our global error handler.
  397 | evt.initEvent(evtType, false, false);
> 398 | fakeNode.dispatchEvent(evt);
  399 | 
  400 | if (windowEventDescriptor) {
  401 |   Object.defineProperty(window, 'event', windowEventDescriptor);

invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:455

  452 | function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
  453 |   hasError = false;
  454 |   caughtError = null;
> 455 |   invokeGuardedCallbackImpl$1.apply(reporter, arguments);
  456 | }
  457 | 
  458 | /**

beginWork$$1
node_modules/react-dom/cjs/react-dom.development.js:23214

  23211 | }
  23212 | 
  23213 | // Run beginWork again.
> 23214 | invokeGuardedCallback(null, beginWork$1, null, current$$1, unitOfWork, expirationTime);
  23215 | 
  23216 | if (hasCaughtError()) {
  23217 |   var replayError = clearCaughtError();

performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js:22208

  22205 |   next = beginWork$$1(current$$1, unitOfWork, renderExpirationTime);
  22206 |   stopProfilerTimerIfRunningAndRecordDelta(unitOfWork, true);
  22207 | } else {
> 22208 |   next = beginWork$$1(current$$1, unitOfWork, renderExpirationTime);
  22209 | }
  22210 | 
  22211 | resetCurrentFiber();

workLoopSync
node_modules/react-dom/cjs/react-dom.development.js:22182

  22179 | function workLoopSync() {
  22180 |   // Already timed out, so perform work without checking if we need to yield.
  22181 |   while (workInProgress !== null) {
> 22182 |     workInProgress = performUnitOfWork(workInProgress);
  22183 |   }
  22184 | }
  22185 | 

renderRoot
node_modules/react-dom/cjs/react-dom.development.js:21875

  21872 | do {
  21873 |   try {
  21874 |     if (isSync) {
> 21875 |       workLoopSync();
  21876 |     } else {
  21877 |       workLoop();
  21878 |     }

runRootCallback
node_modules/react-dom/cjs/react-dom.development.js:21551

  21548 | var prevCallbackNode = root.callbackNode;
  21549 | var continuation = null;
  21550 | try {
> 21551 |   continuation = callback(isSync);
  21552 |   if (continuation !== null) {
  21553 |     return runRootCallback.bind(null, root, continuation);
  21554 |   } else {

flushSyncCallbackQueueImpl/<
node_modules/react-dom/cjs/react-dom.development.js:11354

  11351 |   for (; i < queue.length; i++) {
  11352 |     var callback = queue[i];
  11353 |     do {
> 11354 |       callback = callback(_isSync);
  11355 |     } while (callback !== null);
  11356 |   }
  11357 | });

unstable_runWithPriority
node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:643

  640 | currentPriorityLevel = priorityLevel;
  641 | 
  642 | try {
> 643 |   return eventHandler();
  644 | } finally {
  645 |   currentPriorityLevel = previousPriorityLevel;
  646 | }

runWithPriority$2
node_modules/react-dom/cjs/react-dom.development.js:11306

  11303 | 
  11304 | function runWithPriority$2(reactPriorityLevel, fn) {
  11305 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
> 11306 |   return Scheduler_runWithPriority(priorityLevel, fn);
  11307 | }
  11308 | 
  11309 | function scheduleCallback(reactPriorityLevel, callback, options) {

flushSyncCallbackQueueImpl
node_modules/react-dom/cjs/react-dom.development.js:11350

  11347 | try {
  11348 |   var _isSync = true;
  11349 |   var queue = syncQueue;
> 11350 |   runWithPriority$2(ImmediatePriority, function () {
  11351 |     for (; i < queue.length; i++) {
  11352 |       var callback = queue[i];
  11353 |       do {

flushSyncCallbackQueue
node_modules/react-dom/cjs/react-dom.development.js:11339

  11336 |   if (immediateQueueCallbackNode !== null) {
  11337 |     Scheduler_cancelCallback(immediateQueueCallbackNode);
  11338 |   }
> 11339 |   flushSyncCallbackQueueImpl();
  11340 | }
  11341 | 
  11342 | function flushSyncCallbackQueueImpl() {

scheduleUpdateOnFiber
node_modules/react-dom/cjs/react-dom.development.js:21428

  21425 |       // scheduleCallbackForFiber to preserve the ability to schedule a callback
  21426 |       // without immediately flushing it. We only do this for user-initiated
  21427 |       // updates, to preserve historical behavior of sync mode.
> 21428 |       flushSyncCallbackQueue();
  21429 |     }
  21430 |   }
  21431 | } else {

enqueueSetState
node_modules/react-dom/cjs/react-dom.development.js:13101

  13098 |     flushPassiveEffects();
  13099 |   }
  13100 |   enqueueUpdate(fiber, update);
> 13101 |   scheduleWork(fiber, expirationTime);
  13102 | },
  13103 | enqueueReplaceState: function (inst, payload, callback) {
  13104 |   var fiber = get(inst);

./node_modules/react/cjs/react.development.js/Component.prototype.setState
node_modules/react/cjs/react.development.js:325

  322 |       }
  323 |     }
  324 |   })();
> 325 |   this.updater.enqueueSetState(this, partialState, callback, 'setState');
  326 | };
  327 | 
  328 | /**

JSONStore/_this.handleMittEvent
/Users/Jean-Pierre/repos/montrealphotoclub/.cache/json-store.js:1

> 1 | import React from "react"
  2 | 
  3 | import PageRenderer from "./page-renderer"
  4 | import normalizePagePath from "./normalize-page-path"

socketIo/<
/Users/Jean-Pierre/repos/montrealphotoclub/.cache/socketIo.js:20

  17 | // Try to initialize web socket if we didn't do it already
  18 | try {
  19 |   // eslint-disable-next-line no-undef
> 20 |   socket = io()
  21 | 
  22 |   const didDataChange = (msg, queryData) => {
  23 |     const id =`

**Comment by brotzky** [comment]
Ah, we forgot to export the icon from `icons/index.ts`

I've updated it an published to v0.4.1

**Comment by jpvalery** [comment]
Sorry for not having been more rigorous in this PR but I see that the size of the SVG isn't correct:
image
I thought it would be scaled automatically by Novela, but it seems that the SVG needs to be ~16x16 in the xxx.Icon.ts file
How can I help to get this fixed?

**Comment by brotzky** [comment]
Illl take care of it, JP.
I thought we constrained the SVG but I guess we don't. :D

**Pull request merged**
