### PR TITLE
feat: compability with tinacms

### PR DESCRIPTION
**Pull request by kerycdiaz**
#  **Compatibility with tinacms**

issue #323 Conflict with icons

# Checklist:

* [x] I have followed the guidelines in our [Contributing Guidelines](https://github.com/narative/gatsby-theme-novela/blob/master/CONTRIBUTING.md). _Especially our commitlint_
* [x] I have checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/fix/change.
* [x] I have checked for an open issue related to this. _There isn't one / There is one : #XXX_
* [x] I have performed a self-review of my own code.
* [x] I have performed the necessary tests locally.
* [x] I have linted my code locally prior to submission.
* [x] If applicable, I have commented my code, particularly in hard-to-understand areas

# Type of PR

* [x] Bug fix (_non-breaking change which fixes an issue_)
* [ ] New feature (_adding a feature following a feature-request issue_)
* [ ] Improvement (_improving an existing feature - includes `style:` and `perf:`commits_)
* [ ] Refactor (_rewriting existing code without any feature change_)
* [ ] (!) This change is or requires a documentation update

# Description

Please include a summary of the change and what is changed by this PR. Please also include relevant motivation and context.

## Additional information/context
_If relevant, add any information or context that would be useful to evaluate this PR_

### CODE REVIEW

**Comment by brotzky** [comment]
What's the reasoning for renaming to `nicons`?

Otherwise seems 👍

**Comment by kerycdiaz** [comment]
@brotzky The incompatibility is with https://www.npmjs.com/package/@icons/material which is used by tinacms

**Comment by woosungchoi** [comment]
It would be great if tinacms is supported.

**Comment by kerycdiaz** [comment]
Hi @brotzky , I am still waiting for a response, thank you very much.

**Pull request closed without merging**
