### PR TITLE
[Feature] Newsletter Subscription

### PR DESCRIPTION
**Pull request by jpvalery**
As discussed in #69 - I wanted to add a small feature to allow visitors to subscribe to a mailing list and authors to grow said list. 

I went ahead and tinkered a bit with `gatsby-plugin-mailchimp` and got something decent out of it.
I largely took inspiration from https://thetrevorharmon.com/blog/email-signup-forms-with-gatsby-and-mailchimp  

**Preview**
image
image
I tried to make something fitting your design, but feel free to edit it to your taste.

**How to**
Update `@narative/gatsby-theme-novela/gatsby-config.js` with your MailChimp endpoint
*See plugin documentation [here](https://github.com/benjaminhoffman/gatsby-plugin-mailchimp) on how to get that endpoint*

Currently, for this draft, the component is only on the bottom of the articles, right before the 'More articles' line.  

It's pretty late here in Montréal so I haven't fully tested it yet - hence the draft PR for the moment. 

I'll try to keep working on it over the weekend and hopefully get something working out by the end :) 

*Welcoming and appreciating all constructive criticism and feedback 🙏 *

### CODE REVIEW

**Comment by brotzky** [comment]
This looks awesome!! Fantastic start.

@tcostaco can you take a look over design? Email CTA inline in the article. We have a similar CTA design for narative.co that we can use here.

**Comment by tcostaco** [comment]
This is awesome! Great idea 👏

Thanks so much for the PR, JP. We'll review everything and get the design up early next week.

**Comment by jpvalery** [comment]
You're welcome! Thank you folks for open sourcing that and letting me tinker with it 🙇

**Comment by brotzky** [comment]
@jpvalery here's the final design:
https://www.figma.com/file/FifDf1g8AKnrmJvCMqKY95/Gatsby-Theme-%E2%80%93-Novela?node-id=2041%3A1453

I'll grab this PR and update the design and push up sometime today or tomorrow.

**Comment by jpvalery** [comment]
Freaking dope! 

Is there anything else I can do to help? 

(Since you mention you were going to work on this, I haven't pursued any further testing/QA - let me know if I can assist!)

**Comment by brotzky** [comment]
Not yet.

I'll update the PR and will let you know and then you can do any QA/testing you want to, but it's obviously not required or expected of you. Really appreciate the help so far!

**Comment by jpvalery** [comment]
I just didn't want to leave you with all the less-fun part of work :) If you're good, then I am. Excited to refactor one of my website with this!

**Comment by brotzky** [comment]
Pulled this PR into the repo and going to finish it there.  Thanks so much for the help JP <3

**Pull request closed without merging**
