### PR TITLE
feat(blog): add a category-based generated side menu

### PR DESCRIPTION
**Pull request by PBRT**
# Checklist:

* [x] I have followed the guidelines in our [Contributing Guidelines](https://github.com/narative/gatsby-theme-novela/blob/master/CONTRIBUTING.md). _Especially our commitlint_
* [x] I have checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/fix/change.
* [x] I have checked for an open issue related to this. There isn't one 
* [x] I have performed a self-review of my own code.
* [x] I have performed the necessary tests locally.
* [x] I have linted my code locally prior to submission.
* [x] If applicable, I have commented my code, particularly in hard-to-understand areas

# Type of PR

* [ ] Bug fix (_non-breaking change which fixes an issue_)
* [x] New feature (_adding a feature following a feature-request issue_)
* [ ] Improvement (_improving an existing feature - includes `style:` and `perf:`commits_)
* [ ] Refactor (_rewriting existing code without any feature change_)
* [ ] (!) This change is or requires a documentation update

# Description

This PR is at draft stage, to discuss the possibility to add a generated side menu to the theme, triggered by a button at the top-right corner. I've added it into my blog and figured out that could be nice to have built in, to facilitate navigation between posts.

I've added three mains things:
1- An optional category field in front-mater at the article level, to group potentials articles together
2- The UI for a side menu, full screen when active, to display all the links available. Quite basic designs, so very happy to update accordingly to the UI guidelines
3- A button at the top right corner to show the menu
4- A parameter in the gatsby-config to enable/disable this feature.

I felt it would be easier to discuss via a draft PR instead of an issue, but happy to close it and open an issue if that's the way to do it.

Here's some screenshots, let me know what you think :) 
Screen Shot 2020-02-09 at 11 53 48
Screen Shot 2020-02-09 at 11 54 04
Screen Shot 2020-02-09 at 11 54 08
Screen Shot 2020-02-09 at 11 54 41

I've added some categories for some articles a bit randomly,  happy to do it properly if the PR gets accepted

## Additional information/context
I'm using a slightly different version on my personal blog, https://traveltrolley.org

### CODE REVIEW

**Comment by eugenejeonme** [comment]
Oh! Nice try! This is to take one category each article.
I think it doesn't overlap feature with the tag I suggested. 👍

**Comment by PBRT** [comment]
@eugenejeonme thanks :) Yeah 100% agree about the UI, it's very primitive at the moment, defo not final. I just want to see first if that make sense to add such a feature after what I'll try to make the UI more compatible with novella :)

**Comment by brotzky** [comment]
Love the concept and highlights some aspects we can improve on in the future with Novela or a different theme. I do agree with @eugenejeonme that it doesn't quite fit the original ethos and design of this theme.

Having said that, we really appreciate the concept and it does bring attention to some future endeavours we can accomplish with Novela as a larger system.
I do want to also thank you for creating a PR and showing your effort that way instead of raising in issue. As a maintainer it's super appreciated <3.

For now I will close this PR and let you explore more variations in your own fork :)

**Comment by PBRT** [comment]
No problem, thanks a lot for commenting :) 

Let me know if in a short term future you're planning to implement something similar, happy to help to make it happen! I'll update the UI in the meantime on my fork ;)

**Pull request closed without merging**
