### PR TITLE
Medium icon support

### PR DESCRIPTION
**Pull request by Mombuyish**
Add Medium social icon support.

### CODE REVIEW

**Comment by brotzky** [comment]
Will add medium icon support, but require a Medium icon.

@tcostaco let me know if you're able to mind a Medium icon we can support

**Comment by johnletey** [comment]
@brotzky [Medium.Icon.tsx](https://github.com/narative/gatsby-theme-novela/blob/master/%40narative/gatsby-theme-novela/src/icons/social/Medium.Icon.tsx)

**Comment by brotzky** [comment]
Doh! I guess I out smarted myself and already added one. Thanks, John <3

**Comment by johnletey** [comment]
You're welcome @brotzky

**Pull request merged**
