### PR TITLE
A way to manually set the icon for social link

### PR DESCRIPTION
**Pull request by mabasic**
When name is specified it uses the name as the icon name, otherwise it detects the name from the URL.

See `www/gatsby-config.js` for example what this does.

It is very useful for shortened links. I can see other use cases also.

### CODE REVIEW

**Comment by brotzky** [comment]
Could you update the docs as well to reflect this? WIth that we can merge :)

**Comment by mabasic** [comment]
Sure thing.

**Comment by mabasic** [comment]
@brotzky Updated readme.

Btw. we could also refresh the readme file. It feels like it is all over the place.

**Comment by brotzky** [comment]
Lovely! thanks <3

**Pull request merged**
