### PR TITLE
[Feature] Netlify CMS Data Source

### PR DESCRIPTION
**Pull request by brotzky**

### CODE REVIEW

**Comment by brotzky** [comment]
This is proving to be more of a headache than I initially guessed. This is mostly due to the fact that we're working on a repo that uses yarn workspaces and the site is not in the root folder _and_ in a separate branch off master.

If anyone wants implement Netlify as a data source i'd suggest forking and seeing how it goes. I don't think I'll investigate further into Netlify CMS unless it's requests a lot more or someone can help

**Comment by brotzky** [comment]
Closing this. No immediate demand and it's frustrating setting up Netlify CMS in yarn workspaces.

**Comment by mostafachatillon** [comment]
Hi, did you add Netlify CMS integration? Otherwise, what do you recommend for 1-click deployment?

**Comment by brotzky** [comment]
No plans to add Netlify, sorry. Iif someone really needs it PRs are welcome ❤️.

Use the starter theme https://github.com/narative/gatsby-starter-novela
and deploy it to Zeit or Netlify. Zeit would probably get you the closest to "1-click deployment".

**Pull request closed without merging**
