### PR TITLE
:lipstick:(article) break word

### PR DESCRIPTION
**Pull request by chengcyber**
# Checklist:

* [x] I have followed the guidelines in our [Contributing Guidelines](https://github.com/narative/gatsby-theme-novela/blob/master/CONTRIBUTING.md). _Especially our commitlint_
* [x] I have checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/fix/change.
* [x] I have checked for an open issue related to this. There is one : https://github.com/narative/gatsby-theme-novela/issues/285
* [x] I have performed a self-review of my own code.
* [x] I have performed the necessary tests locally.
* [x] I have linted my code locally prior to submission.
* [x] If applicable, I have commented my code, particularly in hard-to-understand areas

# Type of PR

* [x] Bug fix (_non-breaking change which fixes an issue_)
* [ ] New feature (_adding a feature following a feature-request issue_)
* [ ] Improvement (_improving an existing feature - includes `style:` and `perf:`commits_)
* [ ] Refactor (_rewriting existing code without any feature change_)
* [ ] (!) This change is or requires a documentation update

# Description

Please include a summary of the change and what is changed by this PR. Please also include relevant motivation and context.

page width exceed in mobile

## Additional information/context
_If relevant, add any information or context that would be useful to evaluate this PR_

before:

after:

### CODE REVIEW

**Comment by chengcyber** [comment]
CI broken. it says

```
error  '@narative/gatsby-theme-novela' should be listed in the project's dependencies. Run 'npm i -S @narative/gatsby-theme-novela' to add it  import/no-extraneous-dependencies
```

But, I don't think it comes from my changes.

**Comment by aleccool213** [comment]
@chengcyber You should post a screenshot of before and after 👍

**Comment by chengcyber** [comment]
@aleccool213 Before/After screenshot added. PTAL, thx.

**Comment by brotzky** [comment]
Appreciate it @chengcyber <3

**Pull request merged**
