### PR TITLE
feat: Commitlint and Lerna for CD

### LINKED ISSUE #109: Continuous Deployment
If you want to try setting up or playing with CD yourself here are my notes.

[Lerna](https://github.com/lerna/lerna) - A tool for managing JavaScript projects with multiple packages

```
yarn add lerna --dev -W
yarn lerna init		=> updates package.json , creates ./packages/ and lerna.json
```

Now remove directory ./packages/

Then update `lerna.json` so it looks like:

```javascript
{
  "workspaces": [
    "www/*",
    "@narative/gatsby-theme-novela"
  ],
  "version": "0.4.6" // or whatever the current version is, it needs to match
}
```

Try running it locally to get an impression, there is a y/n choice where you can prevent the publishing.

```
yarn lerna publish patch --loglevel debug
```
  
You'll see it wil update `package.json` for all workspaces but will not publish `www` because it is private.

### PR DESCRIPTION
**Pull request by jpvalery**
I've been tinkering to fix #109 and #89 based on the previous great work of @bravo-kernel 

I've added commitlint to ensure commits follow conventionalcommits as this will be used for CD. 

I've added Lerna to automate the publishing. This is currently configured to generate a version and then publish it on NPM and GitHub. 

I've never really used Travis before, therefore I'm a bit clueless when it comes to how to configure it to do the automated release. 
I found this https://github.com/lerna/lerna/issues/2022 but would love to have some validation 😅

### CODE REVIEW

**Comment by jpvalery** [comment]
@brotzky fyi this will ultimately require you to configure some tokens and access to do the automatic publishing

**Comment by brotzky** [comment]
Looks great, will configure.

**Comment by brotzky** [comment]
I'm also new to this.. just tried to configure but at a bit of a loss.
Any concrete steps I should do?

**Comment by jpvalery** [comment]
From my understanding, there are 2 things to do:

- [ ] Configure CI to be able to publish autonomously (_See #109 and https://github.com/OHIF/Viewers/blob/master/.circleci/config.yml#L154-L171 mentioned there_).
The example is for circleci but it must be similar in Travis.  

- [ ] Get Lerna to run and publish if the build passes CI and merged

Also, I added you as codeowner in the latest commit to automatically assign you for review and ensure PRs don't get merged without your approval.

**Comment by jpvalery** [comment]
Other resources that might be useful: 
- https://github.com/lerna/lerna/blob/master/.travis.yml
- https://www.gatsbyjs.org/blog/2019-01-01-publish-multiple-gatsby-sites/#now they use Now but maybe this can be changed for yarn publish

Travis doc: 
- https://docs.travis-ci.com/user/deployment/releases
- https://docs.travis-ci.com/user/deployment/npm

Lerna doc
- https://github.com/lerna/lerna/tree/master/commands/publish

**Comment by brotzky** [comment]
@jpvalery this one's on the roadmap for this week. I'm not as comfortable so need a bit of time to look through it and evaluate.

**Comment by jpvalery** [comment]
> @jpvalery this one's on the roadmap for this week. I'm not as comfortable so need a bit of time to look through it and evaluate.

@brotzky thanks for the update! No worries, I totally understand :) This was a bit scary to tackle, but once I started working on it, it got clearer. 

Let me know if there's anything I can do to help--do not hesitate to email me if you have any questions!

**Comment by brotzky** [comment]
Going to merge and figure it out :D

**Comment by jpvalery** [comment]
@brotzky yolo :shipit: - Don't hesitate to reach out if I can help in any way!

**Comment by brotzky** [comment]
Looks like it's working on master :)
Ran a couple tests and it seems to auto publish on MRs

**Comment by jpvalery** [comment]
Awesome! So happy to see this live and to be a contributor :)

**Comment by jpvalery** [comment]
Also sidenote: there's an opportunity to improve from there by automating the changelog generation and populating the release with it. Might get on that when I have some spare time 🤓

**Comment by jpvalery** [comment]
@brotzky I noticed that Lerna was publishing a release for `www` as well - is that intended behavior?

**Comment by brotzky** [comment]
No :|

**Comment by brotzky** [comment]
Strange, it seems like Lerna doesn't support publishing from a single package. That's a bit annoying.

**Comment by jpvalery** [comment]
Dang. I was thinking that https://github.com/narative/gatsby-theme-novela/blob/master/lerna.json#L4 would allow Lerna to ignore `www`

**Pull request merged**
